[package]
name = "axum-codec"
version = "0.0.0"
edition = "2021"
description = "A multi-codec extractor and response writer for Axum"
license = "MIT OR Apache-2.0"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
bincode = "1.3.3"
bitcode = "0.6.0"
rmp-serde = "1"
serde = "1.0.204"
serde_json = "1"
