[package]
name = "aide-validator"
version = "0.1.0"
edition = "2021"

[dependencies]
aide = { version = "0.14", features = ["axum"] }
axum = "0.8"
serde = { version = "1", features = ["derive", "rc"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
axum-codec = { path = "../..", features = ["full-codecs", "macros", "aide", "validator"] }
