on:
  push:
    paths:
      - '**.rs'
      - '**.toml'
      - '**.yml'
      - '.git*'
      - 'Cargo.lock'
      - 'README.md' # it's included in the crate root
    branches:
      - main

name: ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup rust toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: rustfmt, clippy
      - name: setup cache
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-rustc-${{ steps.toolchain.outputs.cachekey }}

      - name: install cargo hack
        if: steps.cache.outputs.cache-hit != 'true'
        run: cargo install cargo-hack --locked

      - name: cargo hack
        run: cargo hack check --feature-powerset --no-dev-deps
      - name: cargo test
        run: cargo test
      - name: cargo fmt
        run: cargo fmt --all -- --check
      - name: cargo clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
